%YAML 1.0
---
# CONFIG 0
anchor0:
  id: 0
  fix: true
  p_AinG: [1.230547, -3.336988, 0.691426]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor1:
  id: 1
  fix: true
  p_AinG: [-1.850691, 3.050118, 0.570200]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor2:
  id: 2
  fix: true
  p_AinG: [0.906399, 3.055354, 0.318370]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor3:
  id: 3
  fix: true
  p_AinG: [1.834993, 1.563271, 0.310056]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor4:
  id: 4
  fix: true
  p_AinG: [-0.608059, 0.019197, 0.508402]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor5:
  id: 5
  fix: true
  p_AinG: [0.035641, -5.174972, 0.717479]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor6:
  id: 11
  fix: true
  p_AinG: [-1.514800, -4.278711, 0.466902]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.0005
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02



# ORIGINAL
# anchor0:
#   id: 19333
#   fix: true
#   p_AinG: [2.97,1.44,2.13]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.0005 # 0.02 for random_0
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02

# anchor1:
#   id: 22660
#   fix: false
#   p_AinG: [-2.45,3.75,1.53]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.0005
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02

# anchor2:
#   id: 19110
#   fix: true
#   p_AinG: [-0.71,-0.93,0.25]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.0005
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02

# anchor3:
#   id: 7435
#   fix: false
#   p_AinG: [-2.19,-4.16,1.22]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.0005
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02
