verbosity: "DEBUG"
config: "miluv"
base_path: "/root/datasets"

# Camera Settings
max_cameras: 2
use_stereo: true
num_pts: 200 # default = 200

#  Bag settings
bag_start: 0
dataset: "1d"
robot: "ifo001"
dobag: true
bag: "ifo001_uncompressed.bag"
gt_topic: "/ifo001/vrpn_client_node/ifo001/pose"

dotime: true
dosave: true
dosave_global: true
filename_est: "uvio_local_frame_align_rangecost_yawcov_4dofjac_fix_grid_split"
filename_est_global: "uvio_local_frame_align_rangecost_yawcov_4dofjac_fix_grid_split_global"

dolivetraj: true
path_gt: "ifo001_ground_truth.txt"
# path_gt = /root/datasets/{path_est}/{path_gt}

## UWB config names
## YOU HAVE TO CHANGE THESE IN
## ESTIMATOR_CONFIG.YAML
## TODO: Make it an arg of uvio.cpp
## OR: Change the yaml yourself in py_vins
config_uwb: "uwb_config.yaml"
uwb_anchors: "uwb_anchors.yaml"
spline_fname: "spline_grid.bin"



