%YAML 1.0
---

# Initialization options
init:
  rostopic: /uwb_init_ros/uwb_anchors
  n_fixed_anchors: 6
  n_known_anchors: 6 # If >0 then the file uwb_anchors.yaml must be present in the same directory as this file **
  do_schmidt_uwb_anchors: true
  # Alignment parameters
  do_uwb_frame_align: true
  init_inflation_uwb_frame_align: 1.0
  min_dist_to_use_uwb: 0.2
  min_uwb_ranges_for_alignment: 500 #1250 1d 500 1b
  min_fim_eigenvalue: 0.001 # 0.05 1d 
  max_pdop: 0.13 # 0.13 for 1d  0.2 1b  
  # pdop < max_pdop, eig > min_fim_evalue
  # Tag Parameters
  tag_ids: [10, 11] # Number of tags attached to robot
  do_dstwr_uwb: true
  calib_uwb_extrinsics: true # Whether update for all tags
  calib_uwb_biases: false # Estimate uwb biases
  prior_uwb_imu_cov: 0.0001 # Sets for all tags
  uwb_sigma_range: 0.5 # Sets for all tags
  uwb_chi2_multipler: 1.0 

# UWB tag calibration options
tag10:
  rostopic: /ifo001/uwb/range
  calib_uwb_extrinsics: false
  p_UinI: [0.13189, -0.17245, -0.05249] # Position of tag relative to IMU, resolved in IMU frame
  # p_IinG0: [-0.056053, 0.089564, 0.126043]  # Initial position of UAV in global frame (used as offset for known anchors)
  p_IinG0: [0, 0, 0]
  # uwb_sigma_range: 0.2
  prior_uwb_imu_cov: 0.0001
  uwb_chi2_multipler: 1.0

# UWB tag calibration options
tag11:
  rostopic: /ifo001/uwb/range
  calib_uwb_extrinsics: false
  p_UinI: [-0.175, 0.157, -0.053] # Position of tag relative to IMU, resolved in IMU frame
  # p_IinG0: [-0.056053, 0.089564, 0.126043]  # Initial position of UAV in global frame (used as offset for known anchors)
  p_IinG0: [0, 0, 0]
  # uwb_sigma_range: 0.4
  prior_uwb_imu_cov: 0.0001
  uwb_chi2_multipler: 1.0
# UWB tag calibration options
# This is remaining for previous compatibility only
tag0:
  rostopic: /ifo001/uwb/range
  calib_uwb_extrinsics: false
  p_UinI: [0.13189, -0.17245, -0.05249] # Position of tag relative to IMU, resolved in IMU frame
  # p_IinG0: [-0.056053, 0.089564, 0.126043]  # Initial position of UAV in global frame (used as offset for known anchors)
  p_IinG0: [0, 0, 0]
  # uwb_sigma_range: 0.4
  prior_uwb_imu_cov: 0.0001
  uwb_chi2_multipler: 1.0

# Template for anchorN:
#
# anchorN:
#   id: (anchor id)
#   fix: (true/false)
#   p_AinG: [x,y,z] (position of anchor in global frame)
#   const_bias: (const bias close to zero)
#   dist_bias: (distance bias close to zero)
#   prior_p_AinG_cov: (prior variance of anchor position)
#   prior_const_bias_cov: (prior variance of const bias)
#   prior_dist_bias_cov: (prior variance of distance bias)

# # Initialization options
# init:
#   rostopic: /uwb_init_ros/uwb_anchors
#   n_fixed_anchors: 2
#   n_known_anchors: 0 # If >0 then the file uwb_anchors.yaml must be present in the same directory as this file **
#   min_dist_to_use_uwb: 0.5

# # UWB tag calibration options
# tag0:
#   rostopic: /uwb_driver_node/uwb
#   calib_uwb_extrinsics: false
#   p_UinI: [0.01, -0.01, -0.05]
#   p_IinG0: [0.0, 0.0, 0.0]  # Initial position of UAV in global frame (used as offset for known anchors)
#   uwb_sigma_range: 0.5
#   prior_uwb_imu_cov: 0.1
#   uwb_chi2_multipler: 1.0

# ** If n_known_anchors > 0 then the file uwb_anchors.yaml must be present in the same directory as this file
#   The file uwb_anchors.yaml must contain the following information (e.g. for n_known_anchors = 2):
#
# anchor0:
#   id: 19333
#   fix: true
#   p_AinG: [2.97,1.44,2.13]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.05
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02
#
# anchor1:
#   id: 22660
#   fix: true
#   p_AinG: [-2.45,3.75,1.53]
#   const_bias: 0.0
#   dist_bias: 0.0
#   prior_p_AinG_cov: 0.05
#   prior_const_bias_cov: 0.2
#   prior_dist_bias_cov: 0.02
#
#
# Template for anchorN:
#
# anchorN:
#   id: (anchor id)
#   fix: (true/false)
#   p_AinG: [x,y,z] (position of anchor in global frame)
#   const_bias: (const bias close to zero)
#   dist_bias: (distance bias close to zero)
#   prior_p_AinG_cov: (prior variance of anchor position)
#   prior_const_bias_cov: (prior variance of const bias)
#   prior_dist_bias_cov: (prior variance of distance bias)
#
# Note: The anchor ids must be unique and at least two anchors must be fixed (fix: true)
#

# UVioInitializer.cpp:149 [UVIOInit] Using least squares yaw = [1.309] | offset = [0.688, 0.278, -1.348]
# UVioInitializer.cpp:212 [UVIO] VIO-UWB frames aligned, yaw = [1.276] | offset = [0.540, 0.006, -1.265], confidence = [0.0000, 0.0001, 0.0002, 0.0001] 
# UVioInitializer.cpp:212 [UVIO] VIO-UWB frames aligned, yaw = [1.354] | offset = [-0.011, 0.224, -0.227], confidence = [0.0007, 0.0009, 0.0013, 0.0045] 
# UVioManager.cpp:162 [UVIO] Success! VIO-UWB frames aligned after 1001 UWB ranges and 5.747515m travelled.

# UVioInitializer.cpp:149 [UVIOInit] Using least squares yaw = [1.309] | offset = [0.688, 0.274, -1.356]
# UVioInitializer.cpp:212 [UVIO] VIO-UWB frames aligned, yaw = [1.276] | offset = [0.539, 0.007, -1.263], confidence = [0.0000, 0.0001, 0.0002, 0.0001]
# UVioInitializer.cpp:212 [UVIO] VIO-UWB frames aligned, yaw = [1.348] | offset = [-0.002, 0.218, -0.267], confidence = [0.0007, 0.0010, 0.0014, 0.0043] 
# UVioManager.cpp:162 [UVIO] Success! VIO-UWB frames aligned after 1001 UWB ranges and 5.842215m travelled.